### ISSUE TITLE
Loading Data...

### ISSUE THREAD

**Issue by ceovenu** [tarlepp/Taskboard#32]
Hi there,

Sorry - can't get it going. Pls advise...

All good after sails lift,
The default log-in works, but hen the links to Settings, Users and Admin do not work
The apps says "Loading Data..." 

When I click on the logo, In the terminal, it says 
info: transport end (undefined)
info: handshake authorized icoO#$9lkfad2hj4455

I tried adding users to the app mysql database, which appeared to work, but no luck 

I noticed when i lift sails the version is v0.9.16

Thanks and regards,

**Comment by tarlepp** [comment]
Hmm, quite long time for to provide that example. Closing this for now, re-open or create new one if problem is still valid.
